services:
  app:
    image: mv-landing-page
    container_name: mv-landing-page
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - PORT=3050
    restart: unless-stopped